{
 "title": "Payment Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[24h]))",
     "legendFormat": "Last 24 hours"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[12h]))",
     "legendFormat": "Last 12 hours"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1h]))",
     "legendFormat": "Last 1 hour"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "Last 1 minute"
    }
   ]
  },
  {
   "title": "Total Requests / Second",
   "type": "timeseries",
   "description": "Shows the sum of requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      uri!~\"/actuator.*\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "Total Requests / second"
    }
   ]
  },
  {
   "title": "Average Requests / second - Last 30 minutes",
   "type": "barchart",
   "description": "Shows the current average of requests per endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      uri!~\"/actuator.*\"\r\n    }[30m]\r\n  )\r\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Errors 400 and 500 / second",
   "type": "timeseries",
   "description": "Shows the average of errors 400 + 500 per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(http_server_requests_seconds_count{\r\n    status=~\"4..|5..\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "Average of errors 400 + 500 / second"
    }
   ]
  },
  {
   "title": "Total errors %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(rate(http_server_requests_seconds_count{status=~\"4..|5..\"}[$__rate_interval]))\r\n/\r\nsum(rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "1000 * sum(\r\n  rate(\r\n    http_server_requests_seconds_sum{\r\n      uri!~\"/actuator.*\"\r\n    }[$__rate_interval]\r\n  )\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      uri!~\"/actuator.*\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(jvm_memory_used_bytes{area=\"heap\"})\r\n  /\r\n  sum(jvm_memory_max_bytes{area=\"heap\"})\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "Heap Memory usage"
    }
   ]
  },
  {
   "title": "Live Platform Threads and Live Virtual Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live Platform Threads" },
    {
     "expr": "sum(jvm_threads_virtual_live_threads)",
     "legendFormat": "Live Virtual Threads"
    }
   ]
  }
 ]
}