apiVersion: v1
kind: Secret

metadata:
  name: payment-secret

type: Opaque

stringData:
  DATABASE_PASSWORD: payment_password
  REDIS_PASSWORD: redis_password
  NEW_RELIC_LICENSE_KEY: 11f0d5dbcda17524f987d58c2407c71d4e3fNRAL